// GENERATED by scripts/pin_checksums.py. Do not edit by hand.
//
// The SHA-256 of every `fsp` release archive of this package's version, pinned in the
// package itself so `dart run fespalier` can tell a tampered release from a good one. The
// `release-pins` workflow builds the binaries on the release-please PR, and commits this file
// to that PR's branch; merging the PR tags that commit, so the tag carries its own pins.
// A package whose version has no pins here (a development build, or a release PR before its
// pin commit) falls back to the release's `.sha256` file: `pinnedVersion` is another version
// or empty.

/// The version [pinnedChecksums] belongs to, or `''` when nothing is pinned.
const pinnedVersion = '0.9.0';

/// Release target -> SHA-256 of its archive (`fsp-<target>.tar.gz` / `.zip`).
const pinnedChecksums = <String, String>{
  'aarch64-apple-darwin':
      '0f92344a4d30cf157b323433e23e267bb1f37a578a156410fdb662cf48d89612',
  'aarch64-unknown-linux-gnu':
      '6e2501a97fcadf221cd488b0e8e9f7060dcaac75a80330b5a97c976ebf69d521',
  'x86_64-apple-darwin':
      'c4c8b8888c0c501ed882100143f78b1d9486c18e4593855fe1dae6669590648a',
  'x86_64-pc-windows-msvc':
      '34e83f5b96da421bfa72c353ae082b602035d7907afb1cf37fe488ea426a21ce',
  'x86_64-unknown-linux-gnu':
      '93e687d5e4e7de8a62290bffe1ddf739aef268cd66b9e92a4c630441e6abb082',
};
